// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4iZ-oA_gHTSbVsT2QBff6T2CD6mxD2Q',
    appId: '1:1012444985183:android:b6784f5e882c4cf716e8ea',
    messagingSenderId: '1012444985183',
    projectId: 'al-bahrawi-92034',
    storageBucket: 'al-bahrawi-92034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMu4YiztFTfBitwjbgxR8xUIXZJLZLcoY',
    appId: '1:1012444985183:ios:9e6bd8261464868c16e8ea',
    messagingSenderId: '1012444985183',
    projectId: 'al-bahrawi-92034',
    storageBucket: 'al-bahrawi-92034.firebasestorage.app',
    iosBundleId: 'tech.brmja.alBahrawi',
  );

}
