// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDmVsoi2dX9BP7lGjzMA9lSBNiBwPW1CPs",
    appId: "1:147335979279:android:4889173cca29428a211e7a",
    messagingSenderId: "147335979279",
    projectId: "mazad-3arabety",
    storageBucket: "mazad-3arabety.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyA4Cf8iE9l7uS-VijFYJiiAR_4-oLpMmbM",
    appId: "1:147335979279:ios:acd0a050e7ebb3c2211e7a",
    messagingSenderId: "147335979279",
    projectId: "mazad-3arabety",
    storageBucket: "mazad-3arabety.firebasestorage.app",
    iosBundleId: "tech.brmja.baseProject",
  );
}
